import { prisma } from "../../src/lib/prisma";

export async function seedBooks() {
  await prisma.book.createMany({
    data: [
      {
        title: "Tools of Titans",
        author: "Tim Ferriss",
        year: 2016,
        image_url: "https://res.cloudinary.com/dhjxpn70k/image/upload/v1771155065/book_images/Tools_of_Titans.jpg",
      },
      {
        title: "The 5 AM Club",
        author: "Robin Sharma",
        year: 2018,
        image_url: "https://res.cloudinary.com/dhjxpn70k/image/upload/v1760212713/book_images/The_5_AM_Club.jpg",
      },
      {
        title: "Make Your Bed",
        author: "William H. McRaven",
        year: 2017,
        image_url: "https://res.cloudinary.com/dhjxpn70k/image/upload/v1760212712/book_images/Make_Your_Bed.png",
      },
      {
        title: "The Four Agreements",
        author: "Don Miguel Ruiz",
        year: 1997,
        image_url: "https://res.cloudinary.com/dhjxpn70k/image/upload/v1760212712/book_images/The_Four_Agreements.jpg",
      },
      {
        title: "Ego Is the Enemy",
        author: "Ryan Holiday",
        year: 2016,
        image_url: "https://res.cloudinary.com/dhjxpn70k/image/upload/v1760212711/book_images/Ego_Is_the_Enemy.jpg",
      },
      {
        title: "Born a Crime",
        author: "Trevor Noah",
        year: 2016,
        image_url: "https://res.cloudinary.com/dhjxpn70k/image/upload/v1760212709/book_images/Born_a_Crime.jpg",
      },
      {
        title: "Project Hail Mary",
        author: "Andy Weir",
        year: 2021,
        image_url: "https://res.cloudinary.com/dhjxpn70k/image/upload/v1760212707/book_images/Project_Hail_Mary.jpg",
      },
      {
        title: "The Subtle Art of Not Giving a F*ck",
        author: "Mark Manson",
        year: 2016,
        image_url: "https://res.cloudinary.com/dhjxpn70k/image/upload/v1760212705/book_images/The_Subtle_Art_of_Not_Giving_a_Fck.jpg",
      },
      {
        title: "The Midnight Library",
        author: "Matt Haig",
        year: 2020,
        image_url: "https://res.cloudinary.com/dhjxpn70k/image/upload/v1760212710/book_images/The_Midnight_Library.jpg",
      },
      {
        title: "The Silent Patient",
        author: "Alex Michaelides",
        year: 2019,
        image_url: "https://res.cloudinary.com/dhjxpn70k/image/upload/v1760212708/book_images/The_Silent_Patient.jpg",
      },
      {
        title: "Educated",
        author: "Tara Westover",
        year: 2018,
        image_url: "https://res.cloudinary.com/dhjxpn70k/image/upload/v1760212709/book_images/Educated.jpg",
      },
      {
        title: "Inferno",
        author: "Dan Brown",
        year: 2013,
        image_url: "https://res.cloudinary.com/dhjxpn70k/image/upload/v1754165328/book_images/Inferno.jpg",
      },
      {
        title: "Harry Potter and the Sorcerer's Stone",
        author: "J.K. Rowling",
        year: 1997,
        image_url: "https://res.cloudinary.com/dhjxpn70k/image/upload/v1754165326/book_images/Harry_Potter_and_the_Sorcerers_Stone.jpg",
      },
      {
        title: "Think and Grow Rich",
        author: "Napoleon Hill",
        year: 1937,
        image_url: "https://res.cloudinary.com/dhjxpn70k/image/upload/v1754165324/book_images/Think_and_Grow_Rich.jpg",
      },
      {
        title: "The Shining",
        author: "Stephen King",
        year: 1977,
        image_url: "https://res.cloudinary.com/dhjxpn70k/image/upload/v1754165322/book_images/The_Shining.jpg",
      },
      {
        title: "The Road",
        author: "Cormac McCarthy",
        year: 2006,
        image_url: "https://res.cloudinary.com/dhjxpn70k/image/upload/v1754165319/book_images/The_Road.jpg",
      },
      {
        title: "Dune",
        author: "Frank Herbert",
        year: 1965,
        image_url: "https://res.cloudinary.com/dhjxpn70k/image/upload/v1754165317/book_images/Dune.jpg",
      },
      {
        title: "The Girl on the Train",
        author: "Paula Hawkins",
        year: 2015,
        image_url: "https://res.cloudinary.com/dhjxpn70k/image/upload/v1754165316/book_images/The_Girl_on_the_Train.jpg",
      },
      {
        title: "The Martian",
        author: "Andy Weir",
        year: 2011,
        image_url: "https://res.cloudinary.com/dhjxpn70k/image/upload/v1754165309/book_images/The_Martian.jpg",
      },
      {
        title: "Gone Girl",
        author: "Gillian Flynn",
        year: 2012,
        image_url: "https://res.cloudinary.com/dhjxpn70k/image/upload/v1754165307/book_images/Gone_Girl.jpg",
      },
      {
        title: "The Great Gatsby",
        author: "F. Scott Fitzgerald",
        year: 1925,
        image_url: "https://res.cloudinary.com/dhjxpn70k/image/upload/v1754164293/book_images/The_Great_Gatsby.jpg",
      },
      {
        title: "The Book Thief",
        author: "Markus Zusak",
        year: 2005,
        image_url: "https://res.cloudinary.com/dhjxpn70k/image/upload/v1754164287/book_images/The_Book_Thief.jpg",
      },
      {
        title: "The Fault in Our Stars",
        author: "John Green",
        year: 2012,
        image_url: "https://res.cloudinary.com/dhjxpn70k/image/upload/v1754164283/book_images/The_Fault_in_Our_Stars.jpg",
      },
      {
        title: "The Power of Now",
        author: "Eckhart Tolle",
        year: 1997,
        image_url: "https://res.cloudinary.com/dhjxpn70k/image/upload/v1754164281/book_images/The_Power_of_Now.jpg",
      },
      {
        title: "Becoming",
        author: "Michelle Obama",
        year: 2018,
        image_url: "https://res.cloudinary.com/dhjxpn70k/image/upload/v1754164280/book_images/Becoming.jpg",
      },
      {
        title: "Man's Search for Meaning",
        author: "Viktor E. Frankl",
        year: 1946,
        image_url: "https://res.cloudinary.com/dhjxpn70k/image/upload/v1754165310/book_images/Mans_Search_for_Meaning.jpg",
      },
      {
        title: "Can't Hurt Me",
        author: "David Goggins",
        year: 2018,
        image_url: "https://res.cloudinary.com/dhjxpn70k/image/upload/v1753728393/book_images/Cant_Hurt_Me.jpg",
      },
      {
        title: "Deep Work",
        author: "Cal Newport",
        year: 2016,
        image_url: "https://res.cloudinary.com/dhjxpn70k/image/upload/v1753726234/book_images/Deep_Work.jpg",
      },
      {
        title: "Rich Dad Poor Dad",
        author: "Robert T. Kiyosaki",
        year: 1997,
        image_url: "https://res.cloudinary.com/dhjxpn70k/image/upload/v1754164289/book_images/Rich_Dad_Poor_Dad.jpg",
      },
      {
        title: "Zero to One",
        author: "Peter Thiel",
        year: 2014,
        image_url: "https://res.cloudinary.com/dhjxpn70k/image/upload/v1753726231/book_images/Zero_to_One.jpg",
      },
      {
        title: "Steve Jobs",
        author: "Walter Isaacson",
        year: 2011,
        image_url: "https://res.cloudinary.com/dhjxpn70k/image/upload/v1754165320/book_images/Steve_Jobs.jpg",
      },
      {
        title: "The Lean Startup",
        author: "Eric Ries",
        year: 2011,
        image_url: "https://res.cloudinary.com/dhjxpn70k/image/upload/v1753726227/book_images/The_Lean_Startup.jpg",
      },
      {
        title: "The Art of War",
        author: "Sun Tzu",
        year: 500,
        image_url: "https://res.cloudinary.com/dhjxpn70k/image/upload/v1753726226/book_images/The_Art_of_War.jpg",
      },
      {
        title: "Meditations",
        author: "Marcus Aurelius",
        year: 180,
        image_url: "https://res.cloudinary.com/dhjxpn70k/image/upload/v1753726225/book_images/Meditations.jpg",
      },
      {
        title: "The Psychology of Money",
        author: "Morgan Housel",
        year: 2020,
        image_url: "https://res.cloudinary.com/dhjxpn70k/image/upload/v1754165305/book_images/The_Psychology_of_Money.jpg",
      },
      {
        title: "Ikigai",
        author: "Héctor García & Francesc Miralles",
        year: 2016,
        image_url: "https://res.cloudinary.com/dhjxpn70k/image/upload/v1754165313/book_images/Ikigai.jpg",
      },
      {
        title: "12 Rules for Life",
        author: "Jordan B. Peterson",
        year: 2018,
        image_url: "https://res.cloudinary.com/dhjxpn70k/image/upload/v1753726217/book_images/12_Rules_for_Life.jpg",
      },
      {
        title: "Start With Why",
        author: "Simon Sinek",
        year: 2009,
        image_url: "https://res.cloudinary.com/dhjxpn70k/image/upload/v1753726215/book_images/Start_With_Why.jpg",
      },
      {
        title: "Clean Code",
        author: "Robert C. Martin",
        year: 2008,
        image_url: "https://res.cloudinary.com/dhjxpn70k/image/upload/v1753567287/book_images/Clean_Code.jpg",
      },
      {
        title: "Thinking, Fast and Slow",
        author: "Daniel Kahneman",
        year: 2011,
        image_url: "https://res.cloudinary.com/dhjxpn70k/image/upload/v1753567226/book_images/Thinking_Fast_and_Slow.jpg",
      },
      {
        title: "The Catcher in the Rye",
        author: "J.D. Salinger",
        year: 1951,
        image_url: "https://res.cloudinary.com/dhjxpn70k/image/upload/v1754164286/book_images/The_Catcher_in_the_Rye.jpg",
      },
      {
        title: "The Alchemist",
        author: "Paulo Coelho",
        year: 1988,
        image_url: "https://res.cloudinary.com/dhjxpn70k/image/upload/v1754164290/book_images/The_Alchemist.jpg",
      },
      {
        title: "Sapiens",
        author: "Yuval Noah Harari",
        year: 2011,
        image_url: "https://res.cloudinary.com/dhjxpn70k/image/upload/v1754165329/book_images/Sapiens.png",
      },
      {
        title: "1984",
        author: "George Orwell",
        year: 1949,
        image_url: "https://res.cloudinary.com/dhjxpn70k/image/upload/v1754164295/book_images/1984.jpg",
      },
      {
        title: "The Hobbit",
        author: "J.R.R. Tolkien",
        year: 1937,
        image_url: "https://res.cloudinary.com/dhjxpn70k/image/upload/v1754164284/book_images/The_Hobbit.jpg",
      },
      {
        title: "Pride and Prejudice",
        author: "Jane Austen",
        year: 1813,
        image_url: "https://res.cloudinary.com/dhjxpn70k/image/upload/v1753458256/book_images/Pride_and_Prejudice.jpg",
      },
      {
        title: "The Pragmatic Programmer",
        author: "David Thomas & Andrew Hunt",
        year: 1999,
        image_url: "https://res.cloudinary.com/dhjxpn70k/image/upload/v1753458255/book_images/The_Pragmatic_Programmer.jpg",
      },
      {
        title: "Atomic Habits",
        author: "James Clear",
        year: 2018,
        image_url: "https://res.cloudinary.com/dhjxpn70k/image/upload/v1754164299/book_images/Atomic_Habits.jpg",
      },
      {
        title: "To Kill a Mockingbird",
        author: "Harper Lee",
        year: 1960,
        image_url: "https://res.cloudinary.com/dhjxpn70k/image/upload/v1754164297/book_images/To_Kill_a_Mockingbird.png",
      },
    ],
    skipDuplicates: true,
  });

  console.log("Books seeded successfully");
}